name: Deploy Website

on:
  push:
    branches:
      - main

env:
  SURGE_DOMAIN_STORE: ${{ secrets.SURGE_DOMAIN_STORE }}
  SURGE_DOMAIN_ADMIN_UI: ${{ secrets.SURGE_DOMAIN_ADMIN_UI }}
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Building affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.4.5
      - run: npx nx run-many --all --target=deploy --parallel
